---
# Restart Hadoop.
- hosts: hadoop
  sudo: True
  vars_files:
  - vars/main.yml

  tasks:
  - include: tasks/stop-mapred.yml
  - include: tasks/stop-hdfs.yml
  - include: tasks/start-hdfs.yml
  - include: tasks/start-mapred.yml
