---
# Start Hadoop.
- hosts: cluster 
  sudo: True

  tasks:
  - name: Start impala-state-store on slave
    action: service name=impala-state-store state=stopped
  - name: Start impala-server on slave
    action: service name=impala-server state=started
